import { StyleSheet } from 'react-native';
import Colors from '../../constants/Colors';
import Fonts from '../../constants/Fonts';

export const santaMisaStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  content: {
    paddingHorizontal: 24,
    paddingVertical: 28,
    paddingBottom: 40,
  },
  mainTitle: {
    fontFamily: Fonts.bold,
    fontSize: 22,
    color: Colors.liturgicalRed,
    textAlign: 'center',
    marginBottom: 20,
    letterSpacing: 0.5,
  },
  sectionHeading: {
    fontFamily: Fonts.bold,
    fontSize: 18,
    color: Colors.liturgicalRed,
    textAlign: 'center',
    marginTop: 24,
    marginBottom: 12,
  },
  titulo: {
    fontFamily: Fonts.bold,
    fontSize: 20,
    color: Colors.liturgicalRed,
    marginBottom: 15,
    textAlign: 'center',
  },
  tituloRojo: {
    fontFamily: Fonts.bold,
    fontSize: 20,
    color: Colors.liturgicalRed,
    marginBottom: 15,
    marginTop: 15,
    textAlign: 'center',
  },
  texto: {
    fontFamily: Fonts.regular,
    fontSize: 16,
    lineHeight: 26,
    marginBottom: 10,
    color: '#000000',
    textAlign: 'left',
  },
  textoRojo: {
    fontFamily: Fonts.bold,
    fontSize: 16,
    lineHeight: 26,
    marginBottom: 10,
    color: Colors.liturgicalRed,
    textAlign: 'left',
  },
  textoItalica: {
    fontFamily: Fonts.italic,
    fontSize: 16,
    fontStyle: 'italic',
    lineHeight: 26,
    marginBottom: 10,
    color: '#000000',
    textAlign: 'left',
  },
  textoNegrita: {
    fontFamily: Fonts.bold,
    fontSize: 16,
    lineHeight: 26,
    marginBottom: 10,
    color: '#000000',
    fontStyle: 'italic',
    textAlign: 'left',
  },
  textoRojoItalic: {
    fontFamily: Fonts.italic,
    fontSize: 16,
    fontStyle: 'italic',
    lineHeight: 26,
    marginBottom: 10,
    color: Colors.liturgicalRed,
    textAlign: 'left',
  },
  oracionTexto: {
    fontFamily: Fonts.regular,
    fontSize: 16,
    lineHeight: 26,
    marginBottom: 20,
    color: '#000000',
    textAlign: 'left',
  },
  subtitulo: {
    fontFamily: Fonts.italic,
    fontSize: 16,
    fontStyle: 'italic',
    color: Colors.liturgicalRed,
    marginBottom: 10,
    textAlign: 'center',
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.white,
    paddingVertical: 18,
    paddingHorizontal: 16,
    borderRadius: 6,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.12,
    shadowRadius: 3,
    elevation: 2,
  },
  menuText: {
    fontFamily: Fonts.regular,
    fontSize: 17,
    color: Colors.primary,
    marginLeft: 10,
    flex: 1,
    textAlign: 'center',
  },
  menuItemStacked: {
    backgroundColor: Colors.white,
    paddingVertical: 18,
    paddingHorizontal: 16,
    borderRadius: 6,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.12,
    shadowRadius: 3,
    elevation: 2,
  },
  menuItemStackedText: {
    fontFamily: Fonts.regular,
    fontSize: 17,
    color: Colors.primary,
    textAlign: 'center',
  },
  oracionItem: {
    backgroundColor: Colors.white,
    paddingVertical: 18,
    paddingHorizontal: 16,
    borderRadius: 6,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.12,
    shadowRadius: 3,
    elevation: 2,
  },
  oracionItemTitulo: {
    fontFamily: Fonts.regular,
    fontSize: 17,
    color: Colors.primary,
    textAlign: 'center',
  },
  oracionDetalle: {
    backgroundColor: Colors.white,
    padding: 20,
    borderRadius: 6,
  },
  oracionTitulo: {
    fontFamily: Fonts.bold,
    fontSize: 20,
    color: Colors.liturgicalRed,
    marginBottom: 15,
    textAlign: 'center',
  },
  title: {
    fontFamily: Fonts.bold,
    fontSize: 20,
    color: Colors.liturgicalRed,
    marginBottom: 15,
    textAlign: 'center',
  },
  prayer: {
    fontFamily: Fonts.regular,
    fontSize: 16,
    lineHeight: 26,
    marginBottom: 20,
    color: '#000000',
    textAlign: 'left',
  },
  description: {
    fontFamily: Fonts.regular,
    fontSize: 16,
    lineHeight: 26,
    marginBottom: 16,
    color: '#000000',
    textAlign: 'left',
  },
  autor: {
    fontFamily: Fonts.italic,
    fontSize: 15,
    fontStyle: 'italic',
    color: Colors.secondary,
    textAlign: 'center',
    marginBottom: 16,
  },
  webViewButton: {
    backgroundColor: Colors.liturgicalRed,
  },
  backButton: {
    backgroundColor: Colors.primary,
    paddingVertical: 12,
    paddingHorizontal: 16,
  },
  backButtonText: {
    fontFamily: Fonts.bold,
    color: Colors.white,
    fontSize: 16,
  },
  botonVolver: {
    backgroundColor: Colors.primary,
    padding: 15,
    borderRadius: 8,
    alignItems: 'center',
  },
  botonVolverTexto: {
    fontFamily: Fonts.bold,
    color: Colors.white,
    fontSize: 16,
  },
  opcion: {
    backgroundColor: Colors.white,
    paddingVertical: 18,
    paddingHorizontal: 16,
    borderRadius: 6,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.12,
    shadowRadius: 3,
    elevation: 2,
  },
  opcionTexto: {
    fontFamily: Fonts.regular,
    fontSize: 17,
    color: Colors.primary,
    textAlign: 'center',
  },
  button: {
    backgroundColor: Colors.primary,
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 20,
    alignItems: 'center',
    marginTop: 10,
    marginBottom: 15,
  },
  buttonText: {
    fontFamily: Fonts.bold,
    color: Colors.white,
    fontSize: 16,
  },
  webTitle: {
    fontFamily: Fonts.bold,
    fontSize: 18,
    color: Colors.liturgicalRed,
    marginBottom: 10,
    textAlign: 'center',
  },
  webNote: {
    fontFamily: Fonts.bold,
    fontSize: 15,
    color: '#000000',
    marginBottom: 10,
    textAlign: 'left',
  },
  linkButton: {
    backgroundColor: Colors.primary,
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 20,
    alignItems: 'center',
    marginBottom: 12,
  },
  linkButtonText: {
    fontFamily: Fonts.bold,
    color: Colors.white,
    fontSize: 16,
  },
  plegariaOpcion: {
    borderWidth: 1.5,
    borderColor: Colors.liturgicalRed,
    borderRadius: 8,
    paddingVertical: 14,
    paddingHorizontal: 16,
    marginBottom: 12,
  },
  plegariaOpcionTexto: {
    fontFamily: Fonts.bold,
    fontSize: 16,
    color: Colors.liturgicalRed,
    textAlign: 'center',
  },
  acclamation: {
    fontFamily: Fonts.bold,
    fontSize: 16,
    color: Colors.liturgicalRed,
    textAlign: 'center',
    marginBottom: 8,
  },
});

export default santaMisaStyles;
